---
version: "2"

services:
  i2pd:
    image: chrisbensch/docker-i2pd:latest
    container_name: i2pd
    depends_on:
    ports:
      - '4444:4444' # HTTP Proxy
      - '4445:4445' # SOCKS Proxy
      - '6668:6668' # IRC Irc2P
      - '6669:6669' # IRC Ilita
      - '7070:7070' # Web Console
      - '7654:7654' # I2CP
      - '7656:7656' # SAM
      - '8119:8118' # NTCP
      - '28656:28656' # SSU Custom Port
      - '28657:28657' # SSU2 Custom Port
    mem_limit: 512m
    volumes:
      - ./appdata/etc:/etc/i2pd
      - ./appdata/var:/var/lib/i2pd
    restart: unless-stopped
  tor-proxy:
    image: chrisbensch/docker-tor-proxy:latest
    container_name: tor-proxy
    ports:
      - '9050:9050'
      - '9051:9051'
    mem_limit: 512m
    restart: unless-stopped
